### ISSUE TITLE
Support node v6.3.*

### ISSUE THREAD

**Issue by ChopperLee2011** [Wiredcraft/bunyan-logger#5]
Our team starts to use node version 6+, and this lib can not run be installed on that node version.
Mostly because of [node-bynyan-syslog issue ](https://github.com/mcavage/node-bunyan-syslog/issues/39), needs to fix this problem before continuing use this lib.

**Comment by ChopperLee2011** [comment]
bunyan-syslog supported node v6, but do not push the latest code to npm, so let us use my forked version in case its master branch changed for some reason

**Comment by xavierchow** [comment]
I asked here: https://github.com/mcavage/node-bunyan-syslog/pull/41, 
BTW, where is your forked version?

**Comment by ChopperLee2011** [comment]
the latest version is v0.3.1, but the do the update nan version after release this version, so i just fork the master branch.
